services:
  postgres:
    image: postgres:15
    container_name: pizza-app-db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: pizza-app
    ports:
      - "5432:5432"
    volumes:
        - ~/Documents/postgres-data:/var/lib/postgresql/data
